# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Mosu.blog
tagline:          ''
description:      ''
url:              https://mosu.blog
baseurl:          /

author:
  name:           'mosu'
  url:            https://www.instagram.com/chongin12/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chongin12/chongin12.github.io

timezone:

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag